;; -- Reed-Solomon ----------------------------------------------------------
;;
;; Constructing and manipulating elements of GF(2^m)
;; GF(2^m) = Fq = F2[X]/(P) where m = deg(P) and q = 2^m
;; P is required to be primitive, not merely irreducible: this means
;; alpha = X generates Fq* (the whole multiplicative group of the
;; field), not just some subgroup of it.
;; created by jkmsk <jkmsk@spinode.fr>, Copyright 2026
;;
;; --------------------------------------------------------------------------

(define-module (reed-solomon gf)
  #:export (make-gf gf-exp gf-log gf-inv gf-add gf-mul))

;; make-gf : primitive-poly -> dispatch
;; Builds the Galois field Fq generated by the primitive polynomial P.
;; Both P and every element of Fq are encoded the same way: a plain
;; integer where bit i is the coefficient of X^i (so an Fq element
;; lives in [0, 2^m-1]); e.g. #b100011101 stands for X^8+X^4+X^3+X^2+1.
(define (make-gf primitive-poly)
  (let* ((m (- (integer-length primitive-poly) 1)) ; degree of P
         (q (ash 1 m))                             ; cardinal of Fq
         (n (- q 1))                               ; order of Fq*
         (exp-table (make-vector (* 2 n) 0))       ; exp-table[i] = exp-table[i mod n] = alpha^i
         (log-table (make-vector q 0)))            ; log-table[alpha^i] = i

    (let loop ((i 0) (x 1))
      (when (< i n)
        ;; next = alpha^(i+1) = X * x: shift multiplies by X, then a single
        ;; conditional xor reduces mod P if degree m is exceeded (next >= q,
        ;; since q = 2^m is the smallest value whose bit m is set)
        (let* ((next (ash x 1))
               (next (if (>= next q) (logxor next primitive-poly) next)))
          (vector-set! log-table x i)
          (vector-set! exp-table i x)
          (vector-set! exp-table (+ i n) x)
          (loop (+ i 1) next))))

    (define deg m)
    (define card q)
    (define order n)

    (define (add x y) (logxor x y))

    ;; exp : i -> alpha^i
    (define (exp i) (vector-ref exp-table (modulo i n)))

    ;; log: alpha^i -> i
    (define (log x)
      (when (zero? x) (error "gf-log(0) undefined"))
      (vector-ref log-table x))

    ;; inv: alpha^i -> alpha^-i = alpha^(n-i)
    (define (inv x)
      (when (zero? x) (error "gf-inv(0) undefined"))
      (exp (- n (log x))))

    ;; mul: alpha^i alpha^j -> alpha^(i+j) (0 if either operand is 0)
    (define (mul x y)
      (if (or (zero? x) (zero? y))
          0
          (exp (+ (log x) (log y)))))

    (define (dispatch operation)
      (cond
        ((eq? operation 'deg) deg)
        ((eq? operation 'card) card)
        ((eq? operation 'order) order)
        ((eq? operation 'exp) exp)
        ((eq? operation 'log) log)
        ((eq? operation 'inv) inv)
        ((eq? operation 'add) add)
        ((eq? operation 'mul) mul)
        (else (error "Unknown operation in make-gf" m))))
    dispatch))

(define (gf-exp gf i) ((gf 'exp) i))
(define (gf-log gf x) ((gf 'log) x))
(define (gf-inv gf x) ((gf 'inv) x))
(define (gf-add gf x y) ((gf 'add) x y))
(define (gf-mul gf x y) ((gf 'mul) x y))
