;; -- Reed-Solomon ----------------------------------------------------------
;;
;; Constructing and manipulating elements of GF(2^m)
;; GF(2^m) = Fq = F2[X]/(P) where m = deg(P) and q = 2^m
;; P is required to be primitive, not merely irreducible: this means
;; alpha = X generates Fq* (the whole multiplicative group of the
;; field), not just some subgroup of it.
;; created by jkmsk <jkmsk@spinode.fr>, Copyright 2026
;;
;; --------------------------------------------------------------------------

(define-module (reed-solomon gf)
  #:export (make-gf))

;; make-gf : primitive-poly -> dispatch
;; Builds the Galois field GF(2^m) generated by the primitive polynomial P.
;; Both P and every element of Fq are encoded the same way: a plain
;; integer where bit i is the coefficient of X^i (so an Fq element
;; lives in [0, 2^m-1]); e.g. 100011101 stands for X^8+X^4+X^3+X^2+1.
(define (make-gf primitive-poly)
  (let* ((m (- (integer-length primitive-poly) 1))
         (q (ash 1 m))
         (n (- q 1)))

    (define deg m)
    (define card q)
    (define order n)

    (define (dispatch operation)
      (cond
        ((eq? operation 'deg) deg)
        ((eq? operation 'card) card)
        ((eq? operation 'order) order)
        (else (error "Unknown operation in make-gf" m))))
    dispatch))
