;; -- Reed-Solomon ----------------------------------------------------------
;;
;; Constructing and manipulating elements of GF(2^m)
;; GF(2^m) = Fq = F2[X]/(P) where m = deg(P) and q = 2^m
;; P is required to be primitive, not merely irreducible: this means
;; alpha = X generates Fq* (the whole multiplicative group of the
;; field), not just some subgroup of it.
;; created by jkmsk <jkmsk@spinode.fr>, Copyright 2026
;;
;; --------------------------------------------------------------------------

(define-module (reed-solomon gf)
  #:export (make-gf gf-exp gf-log gf-inv gf-add gf-mul))

(define (make-gf p)
  "Build the Galois field Fq generated by the primitive polynomial P.
Both P and every element of Fq are encoded the same way: a plain integer
where bit i is the coefficient X^i (so an Fq element lives in [0, 2^m-1]);
e.g. #b100011101 stands for X^8+X^4+X^3+X^2+1."
  (let* ((m (- (integer-length p) 1))              ; degree of P
         (q (ash 1 m))                             ; cardinal of Fq
         (n (- q 1))                               ; order of Fq*
         (exp-table (make-vector (* 2 n) 0))       ; exp-table[i] = exp-table[i mod n] = alpha^i
         (log-table (make-vector q 0)))            ; log-table[alpha^i] = i

    (let loop ((i 0) (x 1))
      (when (< i n)
        ;; next = alpha^(i+1) = X * x: shift multiplies by X, then a single
        ;; conditional xor reduces mod P if degree m is exceeded (next >= q,
        ;; since q = 2^m is the smallest value whose bit m is set)
        (let* ((next (ash x 1))
               (next (if (>= next q) (logxor next p) next)))
          (vector-set! log-table x i)
          (vector-set! exp-table i x)
          (vector-set! exp-table (+ i n) x)
          (loop (+ i 1) next))))

    (define deg m)
    (define card q)
    (define order n)

    (define (add a b)
      "Return the sum of A and B in Fq."
      (logxor a b))

    (define (exp i)
      "Return alpha^I, the I-th power of the primitive element alpha (= X)."
      (vector-ref exp-table (modulo i n)))

    (define (log a)
      "Return the discrete logarithm of A in base alpha, i.e. the I such that alpha^I = A."
      (when (zero? a) (error "gf-log(0) undefined"))
      (vector-ref log-table a))

    (define (inv a)
      "Return the multiplicative inverse of A in Fq."
      (when (zero? a) (error "gf-inv(0) undefined"))
      (exp (- n (log a))))

    (define (mul a b)
      "Return the product of A and B in Fq."
      (if (or (zero? a) (zero? b))
          0
          (exp (+ (log a) (log b)))))

    (define (dispatch operation)
      (case operation
        ((deg) deg)
        ((card) card)
        ((order) order)
        ((exp) exp)
        ((log) log)
        ((inv) inv)
        ((add) add)
        ((mul) mul)
        (else (error "Unknown operation in make-gf" operation))))
    dispatch))

(define (gf-exp gf i)
  "Return alpha^I, computed in the field GF."
  ((gf 'exp) i))

(define (gf-log gf a)
  "Return the discrete logarithm of A in base alpha, in the field GF."
  ((gf 'log) a))

(define (gf-inv gf a)
  "Return the multiplicative inverse of A in the field GF."
  ((gf 'inv) a))

(define (gf-add gf a b)
  "Return the sum of A and B in the field GF."
  ((gf 'add) a b))

(define (gf-mul gf a b)
  "Return the product of A and B in the field GF."
  ((gf 'mul) a b))
